apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hydra.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "hydra.labels" . | indent 4 }}
data:
  "config.yaml": |
  {{- with .Values.hydra.config -}}
    {{- if .Values.hydra.config.secrets }}
         {{- (unset .Values.hydra.config "secrets") }}
    {{- end}}
    {{- if .Values.hydra.config.secrets.dsn }}
         {{- (unset .Values.hydra.config "dsn") }}
    {{- end}}
    {{- toYaml . | nindent 4 }}
  {{- end -}}

