apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hydra.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "hydra.labels" . | indent 4 }}
data:
  "config.yaml": |
  {{- with .Values.hydra.config -}}
    {{- $issuer := (unset .Values.hydra.config "secrets") -}}
    {{- $issuer2 := ( unset .Values.hydra.config "dsn") -}}
    {{- toYaml . | nindent 4 }}
  {{- end -}}

